export const mockJobPostings = {
  count: 15,
  hits: [
    {
      company_name: "Louis Vuitton",
      formatted_relative_time: "Just posted",
      id: "1553306bc5c74baa",
      link: "/job/1553306bc5c74baa?locality=us",
      locality: "us",
      location: "Chicago, IL",
      pub_date_ts_milli: 1721710800000,
      salary: {},
      title: "TEAM MANAGER - NORDSTROM",
    },
    {
      company_name: "Louis Vuitton",
      formatted_relative_time: "Just posted",
      id: "c01189f07fbfefc0",
      link: "/job/c01189f07fbfefc0?locality=us",
      locality: "us",
      location: "Skokie, IL",
      pub_date_ts_milli: 1721710800000,
      salary: {},
      title: "STORE MANAGER - OLD ORCHARD",
    },
    {
      company_name: "Microsoft",
      formatted_relative_time: "Just posted",
      id: "5c68c851bf4d9931",
      link: "/job/5c68c851bf4d9931?locality=us",
      locality: "us",
      location: "Chicago, IL 60601",
      pub_date_ts_milli: 1721710800000,
      salary: {
        max: 163300,
        min: 75100,
        type: "yearly",
      },
      title: "Environmental, Health, and Safety Manager",
    },
    {
      company_name: "TikTok",
      formatted_relative_time: "Just posted",
      id: "1a3bc29f12e0e65b",
      link: "/job/1a3bc29f12e0e65b?locality=us",
      locality: "us",
      location: "Chicago, IL",
      pub_date_ts_milli: 1721710800000,
      salary: {},
      title: "TikTok Shop - Site Operations Manager",
    },
    {
      company_name: "BMO US",
      formatted_relative_time: "Just posted",
      id: "01e73f5b4a7529f2",
      link: "/job/01e73f5b4a7529f2?locality=us",
      locality: "us",
      location: "Chicago, IL 60606",
      pub_date_ts_milli: 1721710800000,
      salary: {
        max: 134500,
        min: 72500,
        type: "yearly",
      },
      title: "Manager, Stress Testing",
    },
    {
      company_name: "OSI Group",
      formatted_relative_time: "Just posted",
      id: "d7fc3d437ca0d5c8",
      link: "/job/d7fc3d437ca0d5c8?locality=us",
      locality: "us",
      location: "Chicago, IL",
      pub_date_ts_milli: 1721710800000,
      salary: {},
      title: "Operations Manager 2nd Shift",
    },
    {
      company_name: "Google",
      formatted_relative_time: "Just posted",
      id: "2717d82f4a0cb283",
      link: "/job/2717d82f4a0cb283?locality=us",
      locality: "us",
      location: "Chicago, IL",
      pub_date_ts_milli: 1721797200000,
      salary: {},
      title: "Team Lead, Legal Investigations Support",
    },
    {
      company_name: "Google",
      formatted_relative_time: "Just posted",
      id: "4d48aa7b7c44620e",
      link: "/job/4d48aa7b7c44620e?locality=us",
      locality: "us",
      location: "Chicago, IL",
      pub_date_ts_milli: 1721797200000,
      salary: {},
      title: "Training Program Manager, Legal Investigations Support",
    },
    {
      company_name: "TikTok",
      formatted_relative_time: "Just posted",
      id: "b82e5fb14980e8af",
      link: "/job/b82e5fb14980e8af?locality=us",
      locality: "us",
      location: "Chicago, IL",
      pub_date_ts_milli: 1721710800000,
      salary: {},
      title: "TikTok Shop- Fulfillment Node Operations Manager",
    },
    {
      company_name: "All Clean Services LLC",
      formatted_relative_time: "Just posted",
      id: "ffc2534cf05e7d2e",
      link: "/job/ffc2534cf05e7d2e?locality=us",
      locality: "us",
      location: "Maywood, IL 60153",
      pub_date_ts_milli: 1721710800000,
      salary: {
        max: 70000,
        min: 55000,
        type: "yearly",
      },
      title: "SR. OPERATIONS MANAGER",
    },
    {
      company_name: "Teriyaki Madness - Vernon Hills",
      formatted_relative_time: "Just posted",
      id: "77c0ec7c0a5322f5",
      link: "/job/77c0ec7c0a5322f5?locality=us",
      locality: "us",
      location: "Vernon Hills, IL",
      pub_date_ts_milli: 1721710800000,
      salary: {
        max: 90000,
        min: 75000,
        type: "yearly",
      },
      title:
        "District Manager - Weekly Pay, Weekends Mandatory, No Late Nights",
    },
    {
      company_name: "DoubleTree by Hilton Chicago O'Hare IL",
      formatted_relative_time: "Just posted",
      id: "2b9be071965caccc",
      link: "/job/2b9be071965caccc?locality=us",
      locality: "us",
      location: "Rosemont, IL 60018",
      pub_date_ts_milli: 1721710800000,
      salary: {},
      title: "Front Desk Supervisor",
    },
    {
      company_name: "Allied Universal® Janitorial Services",
      formatted_relative_time: "Just posted",
      id: "0b9f01879dd4edd1",
      link: "/job/0b9f01879dd4edd1?locality=us",
      locality: "us",
      location: "Glenview, IL 60025",
      pub_date_ts_milli: 1721710800000,
      salary: {
        max: 58240,
        min: 58240,
        type: "yearly",
      },
      title: "Janitorial Project Manager",
    },
    {
      company_name: "Teriyaki Madness",
      formatted_relative_time: "Just posted",
      id: "48092be442afb940",
      link: "/job/48092be442afb940?locality=us",
      locality: "us",
      location: "Lombard, IL",
      pub_date_ts_milli: 1721710800000,
      salary: {},
      title:
        "District Manager - Weekly Pay, Weekends Mandatory, No Late Nights",
    },
    {
      company_name: "Accenture",
      formatted_relative_time: "Just posted",
      id: "4e52f7847e671c40",
      link: "/job/4e52f7847e671c40?locality=us",
      locality: "us",
      location: "Chicago, IL",
      pub_date_ts_milli: 1721710800000,
      salary: {},
      title: "Junior Project Manager, Email Coordinator",
    },
  ],
  indeed_final_url:
    "https://www.indeed.com/jobs?q=manager&l=chicago&fromage=1&radius=50&sort=date",
  next_page_id: 2,
  suggest_locality: null,
};

export const mockJobDetails = {
  description: "Detailed job description here.",
  salary: {
    max: 90000,
    min: 75000,
    type: "yearly",
  },
  pub_date_ts_milli: 1721710800000,
};
